apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ool3
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xaqz-tenant/rhtap-demo-app/hacbs-test-project-ool3@sha256:0b6a0db92dd534b8bbae66ba961fcbc5410e0f7621609f6744bd744efc6c72cb
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
